# Generated by Django 3.2.6 on 2022-07-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('closed', models.DateTimeField()),
                ('zone', models.CharField(max_length=50)),
                ('waiter', models.CharField(max_length=200)),
                ('cashier', models.CharField(max_length=200)),
                ('diners', models.IntegerField()),
                ('opened', models.DateTimeField()),
                ('table', models.IntegerField()),
                ('total', models.IntegerField()),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('payments', models.ManyToManyField(to='visual_app.Payment')),
                ('products', models.ManyToManyField(to='visual_app.Product')),
            ],
        ),
    ]
