# Generated by Django 3.2.6 on 2022-07-04 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='id',
            new_name='sale_id',
        ),
    ]
