# Generated by Django 3.2.6 on 2022-07-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual_app', '0002_rename_id_sale_sale_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
    ]
